### ISSUE TITLE
Review  django-password-policies-validator main ê意見

### ISSUE THREAD

**Issue by sih4sing5hong5** [i3thuan5/django-password-policies-validator#4]
## 1.
`password_policies.password_validation.ComplexityValidator`，檔名一般會號做`password_policies.validation.ComplexityValidator'`

## 2
`password_policies/settings_checkmigrations.py`無需要包tī `pypi`，而且應該閣有別ê檔案，所以django試驗設定檔另外一ê檔案簿仔就好。

## 3 參數
https://github.com/i3thuan5/django-password-policies-validator/blob/a9d7121dbcb6f5ca5d935863e4fed84b997be9ce/password_policies/password_validation.py#L9

參數照`django-axes`ê做法，攏用`getattr(settings, 'PASSWORD_POLICIES_MIN_CHAR_TYPES', default=4)`設定，
抑是django有另外建議？

## 4 Symbol
SYMBOL用`[^0-9a-zA-Z]`敢會較好bat？抑是有其他考慮？

**Comment by niauah** [comment]
3. 
django本底的validator mā是用`OPTIONS` 傳--ê，設定方式說明：[Enabling password validation](https://docs.djangoproject.com/en/4.1/topics/auth/passwords/#enabling-password-validation)
```py
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 9,
        }
    },
```

[Writing your own validator](https://docs.djangoproject.com/en/4.1/topics/auth/passwords/#writing-your-own-validator)
> Any items in the `OPTIONS` in [`AUTH_PASSWORD_VALIDATORS`](https://docs.djangoproject.com/en/4.1/ref/settings/#std-setting-AUTH_PASSWORD_VALIDATORS) for your validator will be passed to the constructor. All constructor arguments should have a default value.

**Comment by niauah** [comment]
## 1
> `password_policies.password_validation.ComplexityValidator`，檔名一般會號做`password_policies.validation.ComplexityValidator'`

檔名我是參考django 本底--ê：`'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'`。

**Comment by sih4sing5hong5** [comment]
了解，`3` ê寫法確實較好，kā validator kah設定寫做伙～

**Comment by sih4sing5hong5** [comment]
Aray~
